
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 14 17:24:22 CST 2013
//----------------------------------------------------

package appetizer.syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int TIMES = 4;
  public static final int LT = 9;
  public static final int NE = 8;
  public static final int SEMICOLON = 17;
  public static final int PLUS = 2;
  public static final int INT = 18;
  public static final int RBRACE = 16;
  public static final int RPAREN = 14;
  public static final int RETURN = 20;
  public static final int IF = 19;
  public static final int LPAREN = 13;
  public static final int GT = 10;
  public static final int LBRACE = 15;
  public static final int ID = 22;
  public static final int LE = 11;
  public static final int NUM = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int GE = 12;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 6;
  public static final int EQ = 7;
}

